[project]
name = "llm"
version = "0.1.0"
description = "LLM Zoomcamp"
readme = "README.md"
authors = [
    { name = "asilbek", email = "as.yunusov@agmk.uz" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=3.26.0",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
]

[project.scripts]
llm = "llm:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
